CREATE TABLE IF NOT EXISTS `books` (
    `book_id` int(10) NOT NULL AUTO_INCREMENT,
    `title` varchar(100) NOT NULL ,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`book_id`)
)
